// source: aserto/authorizer/v2/api/decision_logs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var aserto_authorizer_v2_api_policy_context_pb = require('../../../../aserto/authorizer/v2/api/policy_context_pb.js');
goog.object.extend(proto, aserto_authorizer_v2_api_policy_context_pb);
var aserto_authorizer_v2_api_identity_context_pb = require('../../../../aserto/authorizer/v2/api/identity_context_pb.js');
goog.object.extend(proto, aserto_authorizer_v2_api_identity_context_pb);
var aserto_authorizer_v2_api_policy_instance_pb = require('../../../../aserto/authorizer/v2/api/policy_instance_pb.js');
goog.object.extend(proto, aserto_authorizer_v2_api_policy_instance_pb);
goog.exportSymbol('proto.aserto.authorizer.v2.api.Decision', null, global);
goog.exportSymbol('proto.aserto.authorizer.v2.api.DecisionPolicy', null, global);
goog.exportSymbol('proto.aserto.authorizer.v2.api.DecisionUser', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aserto.authorizer.v2.api.Decision = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aserto.authorizer.v2.api.Decision, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aserto.authorizer.v2.api.Decision.displayName = 'proto.aserto.authorizer.v2.api.Decision';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aserto.authorizer.v2.api.DecisionUser = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aserto.authorizer.v2.api.DecisionUser, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aserto.authorizer.v2.api.DecisionUser.displayName = 'proto.aserto.authorizer.v2.api.DecisionUser';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aserto.authorizer.v2.api.DecisionPolicy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aserto.authorizer.v2.api.DecisionPolicy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aserto.authorizer.v2.api.DecisionPolicy.displayName = 'proto.aserto.authorizer.v2.api.DecisionPolicy';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.toObject = function(opt_includeInstance) {
  return proto.aserto.authorizer.v2.api.Decision.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aserto.authorizer.v2.api.Decision} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.Decision.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    timestamp: (f = msg.getTimestamp()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    path: jspb.Message.getFieldWithDefault(msg, 3, ""),
    user: (f = msg.getUser()) && proto.aserto.authorizer.v2.api.DecisionUser.toObject(includeInstance, f),
    policy: (f = msg.getPolicy()) && proto.aserto.authorizer.v2.api.DecisionPolicy.toObject(includeInstance, f),
    outcomesMap: (f = msg.getOutcomesMap()) ? f.toObject(includeInstance, undefined) : [],
    resource: (f = msg.getResource()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    annotationsMap: (f = msg.getAnnotationsMap()) ? f.toObject(includeInstance, undefined) : [],
    tenantId: jspb.Message.getFieldWithDefault(msg, 9, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aserto.authorizer.v2.api.Decision}
 */
proto.aserto.authorizer.v2.api.Decision.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aserto.authorizer.v2.api.Decision;
  return proto.aserto.authorizer.v2.api.Decision.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aserto.authorizer.v2.api.Decision} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aserto.authorizer.v2.api.Decision}
 */
proto.aserto.authorizer.v2.api.Decision.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestamp(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = new proto.aserto.authorizer.v2.api.DecisionUser;
      reader.readMessage(value,proto.aserto.authorizer.v2.api.DecisionUser.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    case 5:
      var value = new proto.aserto.authorizer.v2.api.DecisionPolicy;
      reader.readMessage(value,proto.aserto.authorizer.v2.api.DecisionPolicy.deserializeBinaryFromReader);
      msg.setPolicy(value);
      break;
    case 6:
      var value = msg.getOutcomesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readBool, null, "", false);
         });
      break;
    case 7:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setResource(value);
      break;
    case 8:
      var value = msg.getAnnotationsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setTenantId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aserto.authorizer.v2.api.Decision.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aserto.authorizer.v2.api.Decision} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.Decision.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.aserto.authorizer.v2.api.DecisionUser.serializeBinaryToWriter
    );
  }
  f = message.getPolicy();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.aserto.authorizer.v2.api.DecisionPolicy.serializeBinaryToWriter
    );
  }
  f = message.getOutcomesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeBool);
  }
  f = message.getResource();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getAnnotationsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(8, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 9));
  if (f != null) {
    writer.writeString(
      9,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp timestamp = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getTimestamp = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
*/
proto.aserto.authorizer.v2.api.Decision.prototype.setTimestamp = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearTimestamp = function() {
  return this.setTimestamp(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.hasTimestamp = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional DecisionUser user = 4;
 * @return {?proto.aserto.authorizer.v2.api.DecisionUser}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getUser = function() {
  return /** @type{?proto.aserto.authorizer.v2.api.DecisionUser} */ (
    jspb.Message.getWrapperField(this, proto.aserto.authorizer.v2.api.DecisionUser, 4));
};


/**
 * @param {?proto.aserto.authorizer.v2.api.DecisionUser|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
*/
proto.aserto.authorizer.v2.api.Decision.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.hasUser = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional DecisionPolicy policy = 5;
 * @return {?proto.aserto.authorizer.v2.api.DecisionPolicy}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getPolicy = function() {
  return /** @type{?proto.aserto.authorizer.v2.api.DecisionPolicy} */ (
    jspb.Message.getWrapperField(this, proto.aserto.authorizer.v2.api.DecisionPolicy, 5));
};


/**
 * @param {?proto.aserto.authorizer.v2.api.DecisionPolicy|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
*/
proto.aserto.authorizer.v2.api.Decision.prototype.setPolicy = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearPolicy = function() {
  return this.setPolicy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.hasPolicy = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * map<string, bool> outcomes = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,boolean>}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getOutcomesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,boolean>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearOutcomesMap = function() {
  this.getOutcomesMap().clear();
  return this;};


/**
 * optional google.protobuf.Struct resource = 7;
 * @return {?proto.google.protobuf.Struct}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getResource = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 7));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
*/
proto.aserto.authorizer.v2.api.Decision.prototype.setResource = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearResource = function() {
  return this.setResource(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.hasResource = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * map<string, string> annotations = 8;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getAnnotationsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 8, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearAnnotationsMap = function() {
  this.getAnnotationsMap().clear();
  return this;};


/**
 * optional string tenant_id = 9;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.getTenantId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.setTenantId = function(value) {
  return jspb.Message.setField(this, 9, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Decision} returns this
 */
proto.aserto.authorizer.v2.api.Decision.prototype.clearTenantId = function() {
  return jspb.Message.setField(this, 9, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Decision.prototype.hasTenantId = function() {
  return jspb.Message.getField(this, 9) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.toObject = function(opt_includeInstance) {
  return proto.aserto.authorizer.v2.api.DecisionUser.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aserto.authorizer.v2.api.DecisionUser} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.DecisionUser.toObject = function(includeInstance, msg) {
  var f, obj = {
    context: (f = msg.getContext()) && aserto_authorizer_v2_api_identity_context_pb.IdentityContext.toObject(includeInstance, f),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser}
 */
proto.aserto.authorizer.v2.api.DecisionUser.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aserto.authorizer.v2.api.DecisionUser;
  return proto.aserto.authorizer.v2.api.DecisionUser.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aserto.authorizer.v2.api.DecisionUser} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser}
 */
proto.aserto.authorizer.v2.api.DecisionUser.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new aserto_authorizer_v2_api_identity_context_pb.IdentityContext;
      reader.readMessage(value,aserto_authorizer_v2_api_identity_context_pb.IdentityContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aserto.authorizer.v2.api.DecisionUser.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aserto.authorizer.v2.api.DecisionUser} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.DecisionUser.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      aserto_authorizer_v2_api_identity_context_pb.IdentityContext.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional IdentityContext context = 1;
 * @return {?proto.aserto.authorizer.v2.api.IdentityContext}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.getContext = function() {
  return /** @type{?proto.aserto.authorizer.v2.api.IdentityContext} */ (
    jspb.Message.getWrapperField(this, aserto_authorizer_v2_api_identity_context_pb.IdentityContext, 1));
};


/**
 * @param {?proto.aserto.authorizer.v2.api.IdentityContext|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser} returns this
*/
proto.aserto.authorizer.v2.api.DecisionUser.prototype.setContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser} returns this
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.clearContext = function() {
  return this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser} returns this
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionUser} returns this
 */
proto.aserto.authorizer.v2.api.DecisionUser.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.toObject = function(opt_includeInstance) {
  return proto.aserto.authorizer.v2.api.DecisionPolicy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aserto.authorizer.v2.api.DecisionPolicy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.toObject = function(includeInstance, msg) {
  var f, obj = {
    context: (f = msg.getContext()) && aserto_authorizer_v2_api_policy_context_pb.PolicyContext.toObject(includeInstance, f),
    registryService: jspb.Message.getFieldWithDefault(msg, 2, ""),
    registryImage: jspb.Message.getFieldWithDefault(msg, 3, ""),
    registryTag: jspb.Message.getFieldWithDefault(msg, 4, ""),
    registryDigest: jspb.Message.getFieldWithDefault(msg, 5, ""),
    policyInstance: (f = msg.getPolicyInstance()) && aserto_authorizer_v2_api_policy_instance_pb.PolicyInstance.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aserto.authorizer.v2.api.DecisionPolicy;
  return proto.aserto.authorizer.v2.api.DecisionPolicy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aserto.authorizer.v2.api.DecisionPolicy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new aserto_authorizer_v2_api_policy_context_pb.PolicyContext;
      reader.readMessage(value,aserto_authorizer_v2_api_policy_context_pb.PolicyContext.deserializeBinaryFromReader);
      msg.setContext(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistryService(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistryImage(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistryTag(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegistryDigest(value);
      break;
    case 6:
      var value = new aserto_authorizer_v2_api_policy_instance_pb.PolicyInstance;
      reader.readMessage(value,aserto_authorizer_v2_api_policy_instance_pb.PolicyInstance.deserializeBinaryFromReader);
      msg.setPolicyInstance(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aserto.authorizer.v2.api.DecisionPolicy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aserto.authorizer.v2.api.DecisionPolicy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContext();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      aserto_authorizer_v2_api_policy_context_pb.PolicyContext.serializeBinaryToWriter
    );
  }
  f = message.getRegistryService();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRegistryImage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getRegistryTag();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getRegistryDigest();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getPolicyInstance();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      aserto_authorizer_v2_api_policy_instance_pb.PolicyInstance.serializeBinaryToWriter
    );
  }
};


/**
 * optional PolicyContext context = 1;
 * @return {?proto.aserto.authorizer.v2.api.PolicyContext}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getContext = function() {
  return /** @type{?proto.aserto.authorizer.v2.api.PolicyContext} */ (
    jspb.Message.getWrapperField(this, aserto_authorizer_v2_api_policy_context_pb.PolicyContext, 1));
};


/**
 * @param {?proto.aserto.authorizer.v2.api.PolicyContext|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
*/
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setContext = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.clearContext = function() {
  return this.setContext(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.hasContext = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string registry_service = 2;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getRegistryService = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setRegistryService = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string registry_image = 3;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getRegistryImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setRegistryImage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string registry_tag = 4;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getRegistryTag = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setRegistryTag = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string registry_digest = 5;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getRegistryDigest = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setRegistryDigest = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional PolicyInstance policy_instance = 6;
 * @return {?proto.aserto.authorizer.v2.api.PolicyInstance}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.getPolicyInstance = function() {
  return /** @type{?proto.aserto.authorizer.v2.api.PolicyInstance} */ (
    jspb.Message.getWrapperField(this, aserto_authorizer_v2_api_policy_instance_pb.PolicyInstance, 6));
};


/**
 * @param {?proto.aserto.authorizer.v2.api.PolicyInstance|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
*/
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.setPolicyInstance = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.DecisionPolicy} returns this
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.clearPolicyInstance = function() {
  return this.setPolicyInstance(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.DecisionPolicy.prototype.hasPolicyInstance = function() {
  return jspb.Message.getField(this, 6) != null;
};


goog.object.extend(exports, proto.aserto.authorizer.v2.api);
