// source: aserto/authorizer/v2/api/identity_context.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.aserto.authorizer.v2.api.IdentityContext', null, global);
goog.exportSymbol('proto.aserto.authorizer.v2.api.IdentityType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aserto.authorizer.v2.api.IdentityContext = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aserto.authorizer.v2.api.IdentityContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aserto.authorizer.v2.api.IdentityContext.displayName = 'proto.aserto.authorizer.v2.api.IdentityContext';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.toObject = function(opt_includeInstance) {
  return proto.aserto.authorizer.v2.api.IdentityContext.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aserto.authorizer.v2.api.IdentityContext} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.IdentityContext.toObject = function(includeInstance, msg) {
  var f, obj = {
    identity: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aserto.authorizer.v2.api.IdentityContext}
 */
proto.aserto.authorizer.v2.api.IdentityContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aserto.authorizer.v2.api.IdentityContext;
  return proto.aserto.authorizer.v2.api.IdentityContext.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aserto.authorizer.v2.api.IdentityContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aserto.authorizer.v2.api.IdentityContext}
 */
proto.aserto.authorizer.v2.api.IdentityContext.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentity(value);
      break;
    case 2:
      var value = /** @type {!proto.aserto.authorizer.v2.api.IdentityType} */ (reader.readEnum());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aserto.authorizer.v2.api.IdentityContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aserto.authorizer.v2.api.IdentityContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.IdentityContext.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentity();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * optional string identity = 1;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.getIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.IdentityContext} returns this
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.setIdentity = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional IdentityType type = 2;
 * @return {!proto.aserto.authorizer.v2.api.IdentityType}
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.getType = function() {
  return /** @type {!proto.aserto.authorizer.v2.api.IdentityType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.aserto.authorizer.v2.api.IdentityType} value
 * @return {!proto.aserto.authorizer.v2.api.IdentityContext} returns this
 */
proto.aserto.authorizer.v2.api.IdentityContext.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.aserto.authorizer.v2.api.IdentityType = {
  IDENTITY_TYPE_UNKNOWN: 0,
  IDENTITY_TYPE_NONE: 1,
  IDENTITY_TYPE_SUB: 2,
  IDENTITY_TYPE_JWT: 3
};

goog.object.extend(exports, proto.aserto.authorizer.v2.api);
