// source: aserto/authorizer/v2/api/module.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
goog.exportSymbol('proto.aserto.authorizer.v2.api.Module', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.aserto.authorizer.v2.api.Module = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.aserto.authorizer.v2.api.Module, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.aserto.authorizer.v2.api.Module.displayName = 'proto.aserto.authorizer.v2.api.Module';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.aserto.authorizer.v2.api.Module.prototype.toObject = function(opt_includeInstance) {
  return proto.aserto.authorizer.v2.api.Module.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.aserto.authorizer.v2.api.Module} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.Module.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    raw: jspb.Message.getFieldWithDefault(msg, 2, ""),
    packagePath: jspb.Message.getFieldWithDefault(msg, 3, ""),
    ast: (f = msg.getAst()) && google_protobuf_struct_pb.Value.toObject(includeInstance, f),
    packageRoot: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.aserto.authorizer.v2.api.Module}
 */
proto.aserto.authorizer.v2.api.Module.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.aserto.authorizer.v2.api.Module;
  return proto.aserto.authorizer.v2.api.Module.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.aserto.authorizer.v2.api.Module} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.aserto.authorizer.v2.api.Module}
 */
proto.aserto.authorizer.v2.api.Module.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRaw(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackagePath(value);
      break;
    case 4:
      var value = new google_protobuf_struct_pb.Value;
      reader.readMessage(value,google_protobuf_struct_pb.Value.deserializeBinaryFromReader);
      msg.setAst(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPackageRoot(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.aserto.authorizer.v2.api.Module.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.aserto.authorizer.v2.api.Module.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.aserto.authorizer.v2.api.Module} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.aserto.authorizer.v2.api.Module.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAst();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_struct_pb.Value.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Module.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.setId = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.clearId = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Module.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string raw = 2;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Module.prototype.getRaw = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.setRaw = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.clearRaw = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Module.prototype.hasRaw = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string package_path = 3;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Module.prototype.getPackagePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.setPackagePath = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.clearPackagePath = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Module.prototype.hasPackagePath = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.Value ast = 4;
 * @return {?proto.google.protobuf.Value}
 */
proto.aserto.authorizer.v2.api.Module.prototype.getAst = function() {
  return /** @type{?proto.google.protobuf.Value} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Value, 4));
};


/**
 * @param {?proto.google.protobuf.Value|undefined} value
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
*/
proto.aserto.authorizer.v2.api.Module.prototype.setAst = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.clearAst = function() {
  return this.setAst(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Module.prototype.hasAst = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string package_root = 5;
 * @return {string}
 */
proto.aserto.authorizer.v2.api.Module.prototype.getPackageRoot = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.setPackageRoot = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.aserto.authorizer.v2.api.Module} returns this
 */
proto.aserto.authorizer.v2.api.Module.prototype.clearPackageRoot = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.aserto.authorizer.v2.api.Module.prototype.hasPackageRoot = function() {
  return jspb.Message.getField(this, 5) != null;
};


goog.object.extend(exports, proto.aserto.authorizer.v2.api);
