name: Publish Package to npmjs
on:
  release:
    types: [published]
env:
  VAULT_ADDR: https://vault.eng.aserto.com/

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Read Configuration
        uses: hashicorp/vault-action@v2.5.0
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/npmjs "NPM_TOKEN" | NODE_AUTH_TOKEN;
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: run yarn
        run: |
          yarn
      - name: update package.json version
        run: |
          NEW_VERSION=$(echo "${{ steps.get_release.outputs.tag_name }}" | sed 's/v//')
          yarn version --new-version $NEW_VERSION
      - name: publish to npm
        run: |
          yarn publish --access public
